### ISSUE TITLE
Show a visual confirmation on hitting Copy to Clipboard

### ISSUE THREAD

**Issue by san983** [voxbone-workshop/portal-widget#120]
@san983 commented on [Fri Oct 07 2016](https://github.com/voxbone-workshop/click2vox-com/issues/456)

Today there is no visual confirmation for the user when he clicks on `Copy to Clipboard`, what about using a green bubble for it?

<img width="667" alt="fullscreen_1_5_17__6_03_pm" src="https://cloud.githubusercontent.com/assets/551102/21697527/8a344772-d371-11e6-9ee3-1ddd35d581e2.png">

**Comment by chadwallacehart** [comment]
![image](https://cloud.githubusercontent.com/assets/6531125/22268162/7316604c-e254-11e6-8987-2b88314b6ed6.png)
