### ISSUE TITLE
Move microphone control outside when widget is minimized

### ISSUE THREAD

**Issue by san983** [voxbone-workshop/portal-widget#131]
@fikrifirat commented on [Fri Jan 13 2017](https://github.com/voxbone-workshop/click2vox-com/issues/554)

![image](https://cloud.githubusercontent.com/assets/3737677/21928048/e85e0b7c-d988-11e6-9547-08dbffad4223.png)

When the widget is minimized, users should be able to see the audio level and be able to mute/unmute their microphone.

---

@san983 commented on [Wed Jan 25 2017](https://github.com/voxbone-workshop/click2vox-com/issues/554#issuecomment-275111121)

<img width="494" alt="fullscreen_1_25_17__10_44_am" src="https://cloud.githubusercontent.com/assets/551102/22292733/6bf128dc-e2eb-11e6-86e1-0a53f583ac88.png">

**Comment by fikrifirat** [comment]
@san983 sorry I missed this. A minor thing, the mic controller stays on the widget header when it is minimised and the call is ended by the remote party.

![image](https://cloud.githubusercontent.com/assets/3737677/22323773/53cc3246-e3a5-11e6-894a-ef7e27d77301.png)

**Comment by san983** [comment]
@fikrifirat could you create a ticket for this one please?

**Comment by fikrifirat** [comment]
Created #144
