### ISSUE TITLE
Mic control stays in header when call ended while widget is minimised

### ISSUE THREAD

**Issue by fikrifirat** [voxbone-workshop/portal-widget#144]
@san983  the mic controller stays on the widget header when it is minimised and the call is ended by the remote party.

![image](https://cloud.githubusercontent.com/assets/3737677/22323773/53cc3246-e3a5-11e6-894a-ef7e27d77301.png)

**Comment by san983** [comment]
hey @fikrifirat, is it real the problem with the rating stars showed in the screenshot? or just a problem when you copy pasted the picture?

**Comment by fikrifirat** [comment]
@san983 This is what I've been seeing on Chrome for the past 2 months, at some point we agreed that it was only me who's seeing this problem :)

**Comment by fikrifirat** [comment]
This happens to me on Chrome (56.0.2924.87 (64-bit)) on both normal and incognito modes, FF & Canary works fine.
