### ISSUE TITLE
Handle advanced authentication in new portal widget version

### ISSUE THREAD

**Issue by eos87** [voxbone-workshop/portal-widget#35]
We need to support advanced authentication in these cases:
- ~~If `authUrl` param is provided via POST or GET to the portal widget generator~~ authUrl won't be passed via url, it will be set with an input 
- If `basic_auth=0` we should show an input to request the auth server url to the user to get the auth data. (this should include validating the data return by the endpoint given by the user)

**Comment by san983** [comment]
I'm gonna set an Heroku instance from https://github.com/voxbone/webrtc-node to test this
