### ISSUE TITLE
FAQ and Known Issues links

### ISSUE THREAD

**Issue by chadwallacehart** [voxbone-workshop/portal-widget#68]
The footer displays several links that are broken:
![image](https://cloud.githubusercontent.com/assets/6531125/19325380/dce7647a-9093-11e6-91b9-738062850979.png)
## FAQ - /click2vox/faq

![image](https://cloud.githubusercontent.com/assets/6531125/19325395/f14cd2ba-9093-11e6-8dcc-760b146a5ec1.png)
## Known Issues /click2vox/known-issues

![image](https://cloud.githubusercontent.com/assets/6531125/19325434/1b4ea1ce-9094-11e6-9bab-c4024963bece.png)

Please fix the view references here.
Once that is done @chadwallacehart will update the links as needed.

**Comment by chadwallacehart** [comment]
This needs to be fixed by 14 Oct.

**Comment by san983** [comment]
@chadwallacehart Fixed!
