### ISSUE TITLE
Add text input for color picker

### ISSUE THREAD

**Issue by san983** [voxbone-workshop/portal-widget#97]
Current color picker doesn't allow to exactly add the code for a color, investigate if the current one allows it or add a text input for that.

remember to sync with Click2vox

related https://github.com/voxbone-workshop/portal-widget/issues/71

**Comment by chadwallacehart** [comment]
![image](https://cloud.githubusercontent.com/assets/6531125/22083117/a6a7cc7c-dd98-11e6-948a-7c5ad01d7ea7.png)
